server:
  port: 8004

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SS4-04-StreamingOutput

  ai:
    dashscope:
      api-key: ${aliQwen_key}


