server:
  port: 8003

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SS3-02-ChatModelChatClient

  ai:
    dashscope:
      api-key: ${aliQwen_key}


