server:
  port: 8002

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-02-ollama

  ai:
    dashscope:
      api-key: ${aliQwen_key}
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:cloud


